GET http://localhost:3000/api/users

###
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "Joh Doe",
    "email": "joh@upf.br"
}

###
PUT http://localhost:3000/api/users/1
Content-Type: application/json

{
    "name": "John Doe",
    "email": "jj@jj.com"
}

###
DELETE http://localhost:3000/api/users/1